// Synthetic people for the People domain's structure-and-skills page: 340
// people across the four labs and twelve teams, generated by a seeded function
// so every load is identical. No names: leaders are shown by role and lab.
// Each team's contractor share is its contractorDependency metric value, so the
// People domain page and this page agree team by team.
import { LABS, TEAMS, teamsInLab } from './labs'
import { TEAM_METRICS } from './metrics'
import type { Employment, LabId, Person, Role, RoleGroup, Skill, SkillFlag, SkillId, TeamId } from './types'

export const SKILLS: Skill[] = [
  { id: 'kubernetes', name: 'Kubernetes' },
  { id: 'gcp', name: 'GCP' },
  { id: 'terraform', name: 'Terraform' },
  { id: 'dynatrace', name: 'Dynatrace' },
  { id: 'servicenow', name: 'ServiceNow' },
  { id: 'kafka', name: 'Kafka' },
  { id: 'python', name: 'Python' },
  { id: 'java', name: 'Java' },
  { id: 'dotnet', name: '.NET' },
  { id: 'sql', name: 'SQL' },
  { id: 'dataModelling', name: 'Data modelling' },
  { id: 'bigquery', name: 'BigQuery' },
  { id: 'security', name: 'Security engineering' },
  { id: 'incidentCommand', name: 'Incident command' },
  { id: 'mainframe', name: 'Mainframe' },
  { id: 'agentFrameworks', name: 'Agent frameworks' },
]

export const ROLE_GROUPS: RoleGroup[] = ['Leadership', 'Product and delivery', 'Engineering', 'SRE and operations', 'Data', 'QA']

const ROLE_GROUP: Record<Role, RoleGroup> = {
  'Platform lead': 'Leadership',
  'Lab lead': 'Leadership',
  'Team lead': 'Leadership',
  'Product manager': 'Product and delivery',
  'Delivery manager': 'Product and delivery',
  Architect: 'Engineering',
  Engineer: 'Engineering',
  'Senior engineer': 'Engineering',
  SRE: 'SRE and operations',
  'Data engineer': 'Data',
  Analyst: 'Data',
  'QA engineer': 'QA',
}
export const roleGroupOf = (role: Role): RoleGroup => ROLE_GROUP[role]

/** Team sizes including the team lead; with the platform lead and four lab leads, 340. */
const TEAM_SIZE: Record<TeamId, number> = {
  portal: 34,
  claims: 30,
  policy: 22,
  digital: 30,
  onboarding: 22,
  contact: 32,
  automation: 28,
  agents: 30,
  observability: 24,
  warehouse: 26,
  analytics: 28,
  reporting: 29,
}

/** Weights for the open roles in each lab, in MEMBER_ROLES order. */
const MEMBER_ROLES: Role[] = ['Engineer', 'Senior engineer', 'SRE', 'Data engineer', 'QA engineer', 'Analyst']
const LAB_ROLE_WEIGHTS: Record<LabId, number[]> = {
  core: [30, 14, 30, 3, 8, 5],
  customer: [38, 16, 8, 4, 16, 8],
  payments: [36, 20, 16, 6, 8, 4],
  data: [16, 10, 4, 38, 6, 16],
}

/** The skills each role draws from. Mainframe, .NET and Kafka are in no pool: RARE places them. */
const SKILL_POOL: Record<Role, SkillId[]> = {
  'Platform lead': ['incidentCommand', 'gcp', 'security'],
  'Lab lead': ['incidentCommand', 'gcp', 'security', 'servicenow'],
  'Team lead': ['incidentCommand', 'gcp', 'servicenow', 'python', 'sql'],
  'Product manager': ['servicenow', 'sql', 'dataModelling'],
  'Delivery manager': ['servicenow', 'incidentCommand'],
  Architect: ['gcp', 'terraform', 'kubernetes', 'security', 'dataModelling'],
  Engineer: ['kubernetes', 'gcp', 'terraform', 'python', 'java', 'sql'],
  'Senior engineer': ['kubernetes', 'gcp', 'terraform', 'python', 'java', 'security'],
  SRE: ['kubernetes', 'gcp', 'terraform', 'dynatrace', 'incidentCommand', 'servicenow'],
  'Data engineer': ['sql', 'bigquery', 'dataModelling', 'python', 'gcp'],
  'QA engineer': ['python', 'java', 'sql'],
  Analyst: ['sql', 'dataModelling', 'servicenow', 'bigquery'],
}
/** Agent frameworks sit with the engineers of Agentic Operations only. */
const LAB_ENGINEER_SKILLS: Partial<Record<LabId, SkillId[]>> = { payments: ['agentFrameworks'] }
const ENGINEERS = new Set<Role>(['Engineer', 'Senior engineer'])

/** Skills held by one or two people, each placed on the first person of a role in a team. */
const RARE: { skill: SkillId; teamId: TeamId; role: Role }[] = [
  { skill: 'mainframe', teamId: 'claims', role: 'Senior engineer' },
  { skill: 'dotnet', teamId: 'contact', role: 'Senior engineer' },
  { skill: 'dotnet', teamId: 'contact', role: 'Engineer' },
  { skill: 'kafka', teamId: 'automation', role: 'Senior engineer' },
  { skill: 'kafka', teamId: 'warehouse', role: 'Data engineer' },
]

function seeded(seed: number) {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) >>> 0
    let t = a
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function build(): Person[] {
  const rand = seeded(20260929)
  const weighted = (weights: number[]) => {
    let r = rand() * weights.reduce((a, b) => a + b, 0)
    for (let i = 0; i < weights.length; i++) if ((r -= weights[i]) < 0) return i
    return weights.length - 1
  }
  const skillsFor = (role: Role, labId: LabId | null): SkillId[] => {
    const extra = labId && ENGINEERS.has(role) ? (LAB_ENGINEER_SKILLS[labId] ?? []) : []
    const pool = [...SKILL_POOL[role], ...extra]
    const n = Math.min(pool.length, 1 + Math.floor(rand() * 4))
    const out: SkillId[] = []
    while (out.length < n) {
      const s = pool[Math.floor(rand() * pool.length)]
      if (!out.includes(s)) out.push(s)
    }
    return out
  }
  const gradeFor = (role: Role): Person['grade'] =>
    role === 'Platform lead' || role === 'Lab lead'
      ? 5
      : role === 'Team lead' || role === 'Architect'
        ? 4
        : role === 'Senior engineer' || role === 'Product manager' || role === 'Delivery manager'
          ? 3
          : ((1 + Math.floor(rand() * 3)) as 1 | 2 | 3)

  let seq = 0
  const people: Person[] = []
  const add = (p: Omit<Person, 'id' | 'grade' | 'skills'>) => {
    const person: Person = { ...p, id: `P${String(++seq).padStart(3, '0')}`, grade: gradeFor(p.role), skills: skillsFor(p.role, p.labId) }
    people.push(person)
    return person
  }

  const platformLead = add({ role: 'Platform lead', labId: null, teamId: null, employment: 'permanent', leadLevel: 1, parentId: null })
  for (const lab of LABS) {
    const labLead = add({ role: 'Lab lead', labId: lab.id, teamId: null, employment: 'permanent', leadLevel: 2, parentId: platformLead.id })
    for (const team of teamsInLab(lab.id)) {
      const teamLead = add({ role: 'Team lead', labId: lab.id, teamId: team.id, employment: 'permanent', leadLevel: 3, parentId: labLead.id })
      const members = TEAM_SIZE[team.id] - 1
      const contractors = Math.round((TEAM_SIZE[team.id] * TEAM_METRICS[team.id].contractorDependency.value) / 100)
      const roles: Role[] = ['Product manager', 'Delivery manager', 'Architect']
      while (roles.length < members) roles.push(MEMBER_ROLES[weighted(LAB_ROLE_WEIGHTS[lab.id])])
      // Contractors fill the open roles, never the product, delivery or architect seats.
      const seats = new Set<number>()
      while (seats.size < contractors) seats.add(3 + Math.floor(rand() * (members - 3)))
      roles.forEach((role, i) => {
        const employment: Employment = seats.has(i) ? 'contractor' : 'permanent'
        add({ role, labId: lab.id, teamId: team.id, employment, leadLevel: 0, parentId: teamLead.id })
      })
    }
  }

  for (const r of RARE) {
    const p = people.find((x) => x.teamId === r.teamId && x.role === r.role && !x.skills.includes(r.skill))
    if (!p) throw new Error(`people: no ${r.role} in ${r.teamId} for ${r.skill}`)
    if (p.skills.length >= 4) p.skills.pop()
    p.skills.push(r.skill)
  }
  return people
}

export const PEOPLE: Person[] = build()

export const LEADERS = PEOPLE.filter((p) => p.leadLevel > 0)
export const peopleInLab = (labId: LabId) => PEOPLE.filter((p) => p.labId === labId)
export const peopleInTeam = (teamId: TeamId) => PEOPLE.filter((p) => p.teamId === teamId)

/** Contractor share of a set of people, a whole percentage. */
export const contractorPct = (people: Person[]) =>
  people.length ? Math.round((100 * people.filter((p) => p.employment === 'contractor').length) / people.length) : 0

/** The people a leader's node stands for: everyone for the platform lead, the lab for a lab lead, the team for a team lead. */
export function spanOf(leader: Person): Person[] {
  if (leader.leadLevel === 1) return PEOPLE
  if (leader.leadLevel === 2 && leader.labId) return peopleInLab(leader.labId)
  if (leader.leadLevel === 3 && leader.teamId) return peopleInTeam(leader.teamId)
  return [leader]
}

export interface RoleSlice {
  group: RoleGroup
  count: number
  contractors: number
}

/** A lab's headcount by role group, in ROLE_GROUPS order. */
export const roleComposition = (labId: LabId): RoleSlice[] =>
  ROLE_GROUPS.map((group) => {
    const ps = peopleInLab(labId).filter((p) => roleGroupOf(p.role) === group)
    return { group, count: ps.length, contractors: ps.filter((p) => p.employment === 'contractor').length }
  })

export const SKILL_FLAG_LABEL: Record<SkillFlag, string> = {
  single: 'Single-person',
  thin: 'Thin',
  covered: 'Covered',
}
export const skillFlagFor = (estateCount: number): SkillFlag =>
  estateCount <= 1 ? 'single' : estateCount === 2 ? 'thin' : 'covered'

export interface SkillCoverage {
  skill: Skill
  byLab: Record<LabId, number>
  estate: number
  flag: SkillFlag
}

/** Holders of each critical skill by lab and across the estate, thinnest first. */
export const SKILL_COVERAGE: SkillCoverage[] = SKILLS.map((skill) => {
  const holders = PEOPLE.filter((p) => p.skills.includes(skill.id))
  const byLab = Object.fromEntries(LABS.map((l) => [l.id, holders.filter((p) => p.labId === l.id).length])) as Record<LabId, number>
  return { skill, byLab, estate: holders.length, flag: skillFlagFor(holders.length) }
}).sort((a, b) => a.estate - b.estate || a.skill.name.localeCompare(b.skill.name))

/** Critical skills held by one or two people across the estate. */
export const THIN_SKILLS = SKILL_COVERAGE.filter((s) => s.flag !== 'covered')

/** Open vacancies from the People domain's Vacancies metric, summed across teams. */
export const VACANCIES = TEAMS.reduce((a, t) => a + TEAM_METRICS[t.id].vacancies.value, 0)
